### ISSUE TITLE
Indentation in Configuration/Services.yaml not correct

### ISSUE THREAD

**Issue by vb-benjamin-eyring** [mittwald/smart-extension-builder-feedback#5]
Hi all, 

Martin and I discovered, that the indentation in the Services.yaml is not done correctly, which leads to an error message:

thx, 
Benjamin

TYPO3-Version: 12.4

Error-Message:

![Image](https://github.com/user-attachments/assets/6be856b3-7303-4cb3-8524-12a2c46c4753)

Original Services-yaml that causes the error:

```yaml
# Configuration/Services.yaml:
Visionbites\VbBlog\:
  resource: '../Classes/*'
  exclude: '../Classes/Domain/Model/*'

Visionbites\VbBlog\Controller\:
  resource: '../Classes/Controller/*'
  tags: ['controller.service_arguments']

Visionbites\VbBlog\Domain\Repository\:
  resource: '../Classes/Domain/Repository/*'
  tags: ['doctrine.repository_service']
```

Manually fixed version + addition of _defaults:

```yaml
# Configuration/Services.yaml
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Visionbites\VbBlog\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  Visionbites\VbBlog\Controller\:
    resource: '../Classes/Controller/*'
    tags: ['controller.service_arguments']

  Visionbites\VbBlog\Domain\Repository\:
    resource: '../Classes/Domain/Repository/*'
    tags: ['doctrine.repository_service']`
```
